# _config.yml
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: "Stata-MCP"
description: "Let LLM help you achieve your regression with Stata: AI-Powered Stata Code Generation & Regression Analysis."
url: "https://team.statamcp.com"
